name: Deployment
on:
  workflow_dispatch:     
  push:
    branches:
      - main
      - dev
env:
  MONGODB_DB_NAME: hemidemo
jobs:
  test:
    environment: demo
    container: 
      image: node:20
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb
      MONGODB_PASSWORD: Gunashree_02
      MONGODB_USERNAME: root
      MONGODB_CLUSTER_ADDRESS: mongodb
      PORT: 8080
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: Gunashree_02
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "Mongo DB user: "${{ env.MONGODB_USERNAME }}""
          echo "Mongo DB name: "${{ env.MONGODB_DB_NAME }}""
          echo "Mongo DB password: "${{ secrets.MONGODB_PASSWORD }}""
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "Mongo DB user: "${{ env.MONGODB_USERNAME }}""
          echo "Mongo DB name: "${{ env.MONGODB_DB_NAME }}""
